# Playbook to provision RHOSP instances

- hosts: workstation
  become: yes
  gather_facts: false
  tasks:
  - name: Create frontend instance
    include_role:
      name: osp-servers
      vars_from: frontend.yml
  - name: Create app1 instance
    include_role:
      name: osp-servers
      vars_from: app1.yml
  - name: Create app2 instance
    include_role:
      name: osp-servers
      vars_from: app2.yml
  - name: Create db instance
    include_role:
      name: osp-servers
      vars_from: db.yml

